<?php

namespace OCAS\OCASBundle\Repository;

/**
 * Detail_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Detail_formationRepository extends \Doctrine\ORM\EntityRepository
{
}
