<?php

namespace OCAS\OCASBundle\Repository;

/**
 * Detail_emargementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Detail_emargementRepository extends \Doctrine\ORM\EntityRepository
{
}
