<?php

namespace OCAS\OCASBundle\Repository;

/**
 * Libelle_FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Libelle_FormationRepository extends \Doctrine\ORM\EntityRepository
{
}
