<?php
namespace OCAS\OCASBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends EntityRepository
{

  public function myFindBy($table,$req)
  {
    $query = $this->getEntityManager()
      ->createQueryBuilder('u')
      ->where($table.' LIKE ', '%'.addcslashes($req, '%_').'%')
      ->getQuery();
    return $query->getResult();
  }
}
