<?php
namespace OCAS\OCASBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends EntityRepository
{

  /**
  * Retourne les stagiaires dont le nom contient $req
  */
    public function findByName($req)
    {
        $query = $this->getEntityManager()
                      ->createQuery(
                          "
            SELECT p FROM OCASBundle:Stagiaire p
            WHERE p.nom LIKE :key "
                      );
        $query->setParameter('key', '%'.$req.'%');
        return $query->getResult();
    }
}
