<?php

namespace OCASBundle\Repository;

/**
 * Feuille_emargementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Feuille_emargementRepository extends \Doctrine\ORM\EntityRepository
{
}
