ocas:
    resource: "@OCASBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

dependent_select:
    resource: '@DependentSelectBundle/Resources/config/routing.xml'
    type: xml
